name: $name
version: $version
author: TheGatesDev
api-version: $apiVersion
description: $description
main: io.github.thegatesdev.witheronia.maze_gm.MazeGamemode
depend:
  - Threshold
  - Stacker
  - Actionable
  - Eventador
  - CommandAPI