name: MazeGM
version: '${project.version}'
author: TheGatesDev
api-version: 1.19
main: io.github.thegatesdev.witheronia.maze_gm.MazeGamemode
depend:
  - Stacker
  - Actionable
  - Eventador
  - CommandAPI